name: Eventos
on: [push, pull_request]

jobs:
  detectar-evento:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar tipo de evento
        run:
          echo "El autor es: ${{ github.actor }}"

      - name: Mostrar tipo de evento
        run:
        echo "El evento que me activó fue: ${{ github.event_name }}"
